name: Docker Build
run-name: Docker_${{ inputs.environment }}_${{ inputs.region }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        default: dev
        options:
          - dev
          - qa
          - stg
          - prd

      region:
        type: choice
        description: 'AWS Region'
        required: true
        default: us-east-1
        options:
          - us-east-1
          - eu-central-1
          - eu-west-1
          - us-west-2
          - ap-southeast-2
          - ap-south-1

      dockerfilePath:
        description: 'Path to the Dockerfile'
        default: 'Dockerfile'
        type: string

      isDockerImagePush:
        description: 'Whether to push the Docker image to ECR'
        default: true
        type: boolean

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [self-hosted, Linux, X64,tar-runner]
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR repository name and URI
        id: ecr
        run: |
          REPO_NAME="my-service-${{ inputs.environment }}"
          echo "ECR_REPO=$REPO_NAME" >> $GITHUB_ENV
          echo "ECR_URI=${{ steps.login-ecr.outputs.registry }}/$REPO_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f ${{ inputs.dockerfilePath }} \
            -t $ECR_URI:${{ github.run_id }} .

      - name: Push Docker image to ECR
        if: ${{ inputs.isDockerImagePush }}
        run: |
          docker push $ECR_URI:${{ github.run_id }}
